ports:
  - port: 4943 # ICP mainnet port
    onOpen: open-preview
  - port: 5173 # Flock frontend
    onOpen: open-preview

tasks:
  - name: ICP Project
    init: dfx start --clean && dfx deploy
    command: npm start

  - name: Flock Platform
    init: |
      git config --global core.sshCommand "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -F /dev/null"
      cd flock && npm install
    command: npm run dev

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko
